version: "3.8"


networks:
  elastic:
    driver: bridge
  backend:
    driver: bridge


services:
  backend:
    build:
      context: ./elastic
    networks:
      - backend
    depends_on:
      - elastic
      - kibana

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.3
    container_name: es01
    networks:
      - elastic
    ports:
      - 9200:9200
    tty: true
    stdin_open: true
    deploy:
      resources:
        reservations:
          memory: 4GB

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.3
    container_name: kib01
    networks:
      - elastic
    ports:
      - 5601:5601
    volumes:
      - ./elastic/data:/root/elasticKibana/data