import { c as create_ssr_component, a as add_attribute } from "../../chunks/ssr.js";
import { a as athenaLogo } from "../../chunks/AthenaLogo.js";
const css = {
  code: "#home-canvas.svelte-1qegv6a{display:flex;flex-direction:column;background-color:var(--background-1);padding:40px;gap:40px;height:100vh;align-items:center}img.svelte-1qegv6a{height:25rem;width:25rem}h1.svelte-1qegv6a{color:var(--font-1);font-family:var(--f-ExtraBold), sans-serif;font-size:3rem}p.svelte-1qegv6a{color:var(--font-1);font-family:var(--f-Regular), sans-serif;font-size:2rem}",
  map: '{"version":3,"file":"+page.svelte","sources":["+page.svelte"],"sourcesContent":["<script lang=\\"ts\\">import athenaLogo from \\"$lib/assets/images/AthenaLogo.png\\";\\n<\/script>\\r\\n\\r\\n<div id=\\"home-canvas\\">\\r\\n\\t<img src={athenaLogo} alt=\\"Athena Logo\\" />\\r\\n\\t<h1>Welcome to the Athena Library!</h1>\\r\\n\\t<p>\\r\\n\\t\\tThis library contains information on numerous subjects within Mathematics and Computer Science.\\r\\n\\t</p>\\r\\n</div>\\r\\n\\r\\n<style>\\r\\n\\t#home-canvas {\\r\\n\\t\\tdisplay: flex;\\r\\n\\t\\tflex-direction: column;\\r\\n\\t\\tbackground-color: var(--background-1);\\r\\n\\t\\tpadding: 40px;\\r\\n\\t\\tgap: 40px;\\r\\n\\t\\theight: 100vh;\\r\\n\\t\\talign-items: center;\\r\\n\\t}\\r\\n\\r\\n\\timg {\\r\\n\\t\\theight: 25rem;\\r\\n\\t\\twidth: 25rem;\\r\\n\\t}\\r\\n\\r\\n\\th1 {\\r\\n\\t\\tcolor: var(--font-1);\\r\\n\\t\\tfont-family: var(--f-ExtraBold), sans-serif;\\r\\n\\t\\tfont-size: 3rem;\\r\\n\\t}\\r\\n\\r\\n\\tp {\\r\\n\\t\\tcolor: var(--font-1);\\r\\n\\t\\tfont-family: var(--f-Regular), sans-serif;\\r\\n\\t\\tfont-size: 2rem;\\r\\n\\t}\\r\\n</style>\\r\\n"],"names":[],"mappings":"AAYC,2BAAa,CACZ,OAAO,CAAE,IAAI,CACb,cAAc,CAAE,MAAM,CACtB,gBAAgB,CAAE,IAAI,cAAc,CAAC,CACrC,OAAO,CAAE,IAAI,CACb,GAAG,CAAE,IAAI,CACT,MAAM,CAAE,KAAK,CACb,WAAW,CAAE,MACd,CAEA,kBAAI,CACH,MAAM,CAAE,KAAK,CACb,KAAK,CAAE,KACR,CAEA,iBAAG,CACF,KAAK,CAAE,IAAI,QAAQ,CAAC,CACpB,WAAW,CAAE,IAAI,aAAa,CAAC,CAAC,CAAC,UAAU,CAC3C,SAAS,CAAE,IACZ,CAEA,gBAAE,CACD,KAAK,CAAE,IAAI,QAAQ,CAAC,CACpB,WAAW,CAAE,IAAI,WAAW,CAAC,CAAC,CAAC,UAAU,CACzC,SAAS,CAAE,IACZ"}'
};
const Page = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  $$result.css.add(css);
  return `<div id="home-canvas" class="svelte-1qegv6a" data-svelte-h="svelte-c8jclp"><img${add_attribute("src", athenaLogo, 0)} alt="Athena Logo" class="svelte-1qegv6a"> <h1 class="svelte-1qegv6a">Welcome to the Athena Library!</h1> <p class="svelte-1qegv6a">This library contains information on numerous subjects within Mathematics and Computer Science.</p> </div>`;
});
export {
  Page as default
};
